apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angularapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 80
    nodePort: 31100